services:
  strapiDB:
      image: postgres:15.0-alpine
      container_name: strapiDB
      platform: linux/arm64/v8 # for platform error on Apple M1 chips
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - strapi-data:/var/lib/postgresql/data/
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - app-network
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    depends_on:
       strapiDB:
        condition: service_healthy
    networks:
      - app-network
  
volumes:
  strapi-data:
networks:
  app-network:
    driver: bridge
    name: App-network